global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ai_ocean_app'
    static_configs:
      - targets: ['172.18.0.1:8000']
        labels:
          role: backend

  - job_name: 'ai_ocean_metrics'
    static_configs:
      - targets: ['172.18.0.1:8002']
        labels:
          role: metrics

  - job_name: 'ai_frontend'
    static_configs:
      - targets: ['172.18.0.1:8501']
        labels:
          role: frontend

rule_files:
  - /etc/prometheus/rules/alert_rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
