global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ai_ocean_app'
    static_configs:
      - targets: ['localhost:8000']
        labels:
          role: backend

  - job_name: 'ai_ocean_metrics'
    static_configs:
      - targets: ['localhost:8002']
        labels:
          role: metrics

  - job_name: 'ai_frontend'
    static_configs:
      - targets: ['localhost:8501']
        labels:
          role: frontend
